import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     
      <head>
        <link
          rel="stylesheet"
          href="https://developer.api.autodesk.com/modelderivative/v2/viewers/style.min.css"
          type="text/css"
        />
         <link href="https://cdn.syncfusion.com/ej2/22.1.34/tailwind.css" rel="stylesheet"/>
            <style>{`
          html, body {
            height: 100%;
            margin: 0;
            padding: 0;
            width: 100%;
          }          
        `}</style>
      </head>
      <body className={inter.className}>{children}

      <script src="https://developer.api.autodesk.com/modelderivative/v2/viewers/7.*/viewer3D.min.js"></script>
      </body>

   

    </html>
  );
}
